<?xml version="1.0"?>
<!--
  ArUco Visual Servoing - Differential Drive Robot URDF
  
  This file defines the complete kinematic and dynamic structure of a differential drive
  mobile robot equipped with an onboard camera for ArUco marker-based visual servoing.
  The model includes a base chassis, two independently actuated wheels, a caster wheel for
  stability, and a mounted camera with proper optical frame alignment.
  
  Robot Features:
  - Differential drive locomotion with independent left/right wheel control
  - Camera system with optical frame transformation
  - Caster wheel for stability on uneven surfaces
  - Complete inertial properties for physics simulation
  
  Author: Mohamed Eyad
  Date: December 13, 2025
  License: See package.xml for license information
-->

<robot name="aruco_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ========================================= -->
  <!-- External File Includes                    -->
  <!-- ========================================= -->
  
  <xacro:include filename="$(find aruco_visual_servoing)/urdf/aruco_bot_skid_steer.gazebo.xacro"/>
  <xacro:include filename="$(find aruco_visual_servoing)/urdf/materials.xacro"/>

  <!-- ========================================= -->
  <!-- Robot Geometry Parameters                 -->
  <!-- ========================================= -->
  
  <xacro:property name="WHEEL_RADIUS" value="0.4"/>        <!-- meters -->
  <xacro:property name="WHEEL_WIDTH" value="0.2"/>         <!-- meters -->
  <xacro:property name="BASE_LENGTH" value="2.0"/>         <!-- meters -->
  <xacro:property name="BASE_WIDTH" value="1.0"/>          <!-- meters -->
  <xacro:property name="BASE_HEIGHT" value="0.5"/>         <!-- meters -->
  <xacro:property name="WHEEL_SEPARATION" value="${BASE_WIDTH + WHEEL_WIDTH}"/>
  <xacro:property name="WHEEL_X_OFFSET" value="${(BASE_LENGTH/2) - WHEEL_RADIUS}"/>

  <!-- Mass / inertia approximations -->
  <xacro:property name="BASE_MASS" value="5.0"/>
  <xacro:property name="WHEEL_MASS" value="2.0"/>
  
  <!-- ========================================= -->
  <!-- Mathematical Constants                    -->
  <!-- ========================================= -->
  
  <xacro:property name="PI" value="3.14159265359"/>

  <!-- ========================================= -->
  <!-- Base Footprint and Chassis                -->
  <!-- ========================================= -->
  
  <link name="base_footprint"/>
  
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0 0" rpy="0 0 0.0"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${BASE_LENGTH} ${BASE_WIDTH} ${BASE_HEIGHT}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="${BASE_LENGTH} ${BASE_WIDTH} ${BASE_HEIGHT}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${BASE_MASS}"/>
      <inertia ixx="0.83333" ixy="0" ixz="0" iyy="1.66667" iyz="0" izz="1.66667"/>
    </inertial>
  </link>

  <!-- ========================================= -->
  <!-- Wheel Links                               -->
  <!-- ========================================= -->
  
  <!-- Wheel Macro -->
  <xacro:macro name="wheel_link" params="prefix x_location y_location">
    <link name="${prefix}_wheel">
        <visual>
            <geometry>
                <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${WHEEL_MASS}"/>
            <inertia ixx="0.145833" ixy="0" ixz="0" iyy="0.145833" iyz="0" izz="0.125"/>
        </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="${prefix}_wheel"/>
        <origin xyz="${x_location} ${y_location} 0" rpy="-${PI/2} 0 0"/>
        <axis xyz="0 0 1"/>  
        <limit effort="100" velocity="10.0"/>        
    </joint>
  </xacro:macro>

  <xacro:wheel_link prefix="front_left"  x_location="${WHEEL_X_OFFSET}"  y_location="${WHEEL_SEPARATION/2}"/>
  <xacro:wheel_link prefix="front_right" x_location="${WHEEL_X_OFFSET}"  y_location="-${WHEEL_SEPARATION/2}"/>
  <xacro:wheel_link prefix="rear_left"   x_location="-${WHEEL_X_OFFSET}" y_location="${WHEEL_SEPARATION/2}"/>
  <xacro:wheel_link prefix="rear_right"  x_location="-${WHEEL_X_OFFSET}" y_location="-${WHEEL_SEPARATION/2}"/>

  <!-- ========================================= -->
  <!-- Camera Links                              -->
  <!-- ========================================= -->
  
  <!-- Camera Physical Link -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.2 0.2 0.2"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.2 0.2 0.2"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  
  <!-- Camera Optical Frame (aligned with camera sensor coordinate system) -->
  <link name="camera_link_optical"/>

  <!-- ========================================= -->
  <!-- Robot Joints                              -->
  <!-- ========================================= -->
  
  <!-- Camera Mounting Joint -->
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="0.9 0 0.36" rpy="0 0 0"/>
  </joint>

  <!-- Camera Optical Frame Transformation (ROS standard camera frame alignment) -->
  <joint name="camera_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-${PI/2} 0 -${PI/2}"/>
    <child link="camera_link_optical"/>
    <parent link="camera_link"/>
  </joint>

</robot>