<?xml version="1.0"?>
<robot name="aruco_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- <xacro:include filename="$(find diffbot_gazebo)/urdf/gz/diffbot.gazebo.xacro"/> -->

  <!-- Basic params -->
  <xacro:property name="WHEEL_RADIUS" value="0.4"/> <!-- meters -->
  <xacro:property name="WHEEL_WIDTH" value="0.2"/>
  <xacro:property name="CASTER_RADIUS" value="0.2"/>
  <xacro:property name="BASE_LENGTH" value="2.0"/>
  <xacro:property name="BASE_WIDTH" value="1.0"/>
  <xacro:property name="BASE_HEIGHT" value="0.5"/>
  <xacro:property name="WHEEL_SEPARATION" value="${BASE_WIDTH + WHEEL_WIDTH}"/>
  
  <!-- Mass / inertia approximations -->
  <xacro:property name="BASE_MASS" value="5.0"/>
  <xacro:property name="WHEEL_MASS" value="2.0"/>
  <xacro:property name="CASTER_MASS" value="1.0"/>
  
  <!-- Mathematical constant -->
  <xacro:property name="PI" value="3.14159265359"/>

  <!-- Material colors -->
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>

  <material name="green">
    <color rgba="0.0 0.8 0.0 1.0"/>
  </material>

  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>

  <material name="silver">
    <color rgba="0.75 0.75 0.75 1.0"/>
  </material>

  <material name="orange">
    <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
  </material>

  <material name="brown">
    <color rgba="${222/255} ${207/255} ${195/255} 1.0"/>
  </material>

  <!-- Chassis -->
  <link name="base_footprint"/>
  
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0 0" rpy="0 0 0.0" />
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${BASE_LENGTH} ${BASE_WIDTH} ${BASE_HEIGHT}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="${BASE_LENGTH} ${BASE_WIDTH} ${BASE_HEIGHT}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${BASE_MASS}"/>
        <inertia ixx="0.83333" ixy="0" ixz="0" iyy="1.66667" iyz="0" izz="1.66667"/>
    </inertial>
  </link>

  <!-- Left Wheel -->
  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${WHEEL_MASS}"/>
      <inertia ixx="0.145833" ixy="0" ixz="0" iyy="0.145833" iyz="0" izz="0.125"/>
    </inertial>
  </link>

  <!-- Right Wheel -->
  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${WHEEL_MASS}"/>
      <inertia ixx="0.145833" ixy="0" ixz="0" iyy="0.145833" iyz="0" izz="0.125"/>
    </inertial>
  </link>

  <!-- Caster Wheel -->
  <link name="caster">
    <visual>
      <geometry>
        <sphere radius="${CASTER_RADIUS}"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.2"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${CASTER_MASS}"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- Joints -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="-0.5 ${WHEEL_SEPARATION/2} 0" rpy="-${PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100" velocity="10.0"/>    
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="-0.5 -${WHEEL_SEPARATION/2} 0" rpy="-${PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100" velocity="10.0"/>        
  </joint>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster"/>
    <origin xyz="0.8 0 -0.2" rpy="0 0 0"/>
  </joint>

</robot>